// <auto-generated />
namespace WPF_EF_Rebbit_MSTest_Moq.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IndicatorTypeIsRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndicatorTypeIsRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201907152029145_IndicatorTypeIsRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
